all <- ("quant_norm.4foldpadj1e-3.both.table.eachcellavgcenteredSD_K_G8.reordered")
temp <- as.matrix(read.delim(all,header=TRUE,sep="\t",row.names=1,as.is=TRUE))
library(reshape2)
melted_temp <- melt(temp)
library(ggplot2)
library(scales)
library(cowplot)
png(file="_quant_norm.4foldpadj1e-3.both.table.eachcellavgcenteredSD_K_G8.reordered.-3to3.png",width=192,height=NROW(temp))
ggplot(melted_temp, aes(x=Var2, y=Var1, fill=value)) + geom_tile() + scale_fill_gradient2(low = 'blue', mid = 'white',high = 'red', na.value = 'white', oob=squish, limit = c(-3,3)) + theme_nothing()
dev.off()
